# ------------------------------------------------------------
# youtube_upload.py
# Version: 1.3.0
#
# Changes from 1.2.0:
#   - All config now read from cot_config.py
#   - Quota tracker: log units used to quota_log.json, show before/after
#   - Robust dependency error messages with pip install commands
#   - Draft/unlisted warning on upload with Studio link
#
# Changes from 1.0.0:
#   - get_live_video_metadata: fetch all editable fields
#   - push_metadata_update: always send privacy + all status fields
#   - privacy bug fixed: was never being passed on push
#
# Purpose:
#   Upload videos to YouTube using the YouTube Data API v3.
#   Reads youtube_uploads.csv generated by youtube_meta.py.
#   Handles OAuth authentication, quota limits, and thumbnails.
#
# Features:
#   - Google OAuth2 authentication (one-time browser login)
#   - Reads CSV and uploads pending videos
#   - Sets title, description, tags, category, privacy, license,
#     made_for_kids, comments, thumbnail per video
#   - Prefers video_file_music over video_file_silent
#   - Skips rows already uploaded (tracks in upload_log.json)
#   - Handles YouTube daily quota limit (~6 videos/day free tier)
#     gracefully — saves progress, resume next day
#   - Dry run mode — shows what would be uploaded without doing it
#
# Usage:
#   python youtube_upload.py
#   python youtube_upload.py --dryrun
#
# Setup (one-time):
#   1. Place client_secrets.json in COTCode folder
#   2. Run script — browser opens for Google login
#   3. token.json saved for future runs (no re-login needed)
#
# Dependencies:
#   pip install google-auth google-auth-oauthlib google-auth-httplib2
#   pip install google-api-python-client
#
# Quota notes:
#   - YouTube Data API free quota: 10,000 units/day
#   - Each video upload costs ~1,600 units
#   - Each thumbnail upload costs 50 units
#   - Safe daily limit: ~6 videos with thumbnails
#   - Request higher quota at: console.cloud.google.com
# ------------------------------------------------------------

import os
import sys
import csv
import json
import argparse
import time
from datetime import datetime

try:
    from google.oauth2.credentials import Credentials
    from google_auth_oauthlib.flow import InstalledAppFlow
    from google.auth.transport.requests import Request
    from googleapiclient.discovery import build
    from googleapiclient.http import MediaFileUpload
    from googleapiclient.errors import HttpError
except ImportError:
    print("ERROR: Google API libraries not installed.")
    print("Run:")
    print("  pip install google-auth google-auth-oauthlib google-auth-httplib2")
    print("  pip install google-api-python-client")
    sys.exit(1)


# ------------------------------------------------------------
# CONFIGURATION — edit these to match your setup
# ------------------------------------------------------------

# ── Config loaded from cot_config.py ─────────────────────────
import sys as _sys
_SCRIPTS_DIR_DEFAULT = os.path.dirname(os.path.abspath(__file__))
if _SCRIPTS_DIR_DEFAULT not in _sys.path:
    _sys.path.insert(0, _SCRIPTS_DIR_DEFAULT)

try:
    import cot_config as _cfg
    _cfg.load()
except ImportError:
    _cfg = None

def _c(key, default=''):
    return _cfg.get(key, default) if _cfg else default

def SCRIPTS_DIR():    return _c('SCRIPTS_DIR', _SCRIPTS_DIR_DEFAULT)
def OUTPUT_DIR():     return _c('OUTPUT_DIR', '')
def CSV_PATH():       return _c('CSV_PATH', '')
def CLIENT_SECRETS(): return _c('CLIENT_SECRETS', os.path.join(SCRIPTS_DIR(), 'client_secrets.json'))
def TOKEN_FILE():     return _c('TOKEN_FILE', os.path.join(SCRIPTS_DIR(), 'token.json'))
def UPLOAD_LOG():     return _c('UPLOAD_LOG', os.path.join(OUTPUT_DIR(), 'upload_log.json'))
def QUOTA_LOG():      return os.path.join(OUTPUT_DIR(), 'quota_log.json')

# YouTube API scopes — upload + metadata write + analytics
SCOPES              = [
    "https://www.googleapis.com/auth/youtube",
    "https://www.googleapis.com/auth/youtube.upload",
    "https://www.googleapis.com/auth/youtube.force-ssl",
    "https://www.googleapis.com/auth/yt-analytics.readonly",
]

# Quota safety — stop uploading if remaining units fall below this threshold
QUOTA_SAFETY_BUFFER = 2000      # Stop if fewer than 2000 units remain today
UNITS_PER_UPLOAD    = 1600      # Approximate cost per video upload
UNITS_PER_THUMBNAIL = 50        # Approximate cost per thumbnail upload
DAILY_QUOTA         = 10000     # YouTube free tier daily quota

# Delay between uploads (seconds) — be polite to the API
UPLOAD_DELAY        = 5


# ------------------------------------------------------------
# LOGGING
# ------------------------------------------------------------

def log(msg, also_print=True):
    """Write timestamped message to console and log file."""
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    line      = f"[{timestamp}] {msg}"
    if also_print:
        print(line)
    log_path = os.path.join(OUTPUT_DIR(), "upload_log.txt")
    with open(log_path, "a", encoding="utf-8") as f:
        f.write(line + "\n")


# ------------------------------------------------------------
# UPLOAD LOG — tracks uploaded videos across sessions
# ------------------------------------------------------------

def load_upload_log():
    """
    Load the upload log JSON.
    Returns dict: { folder_name: { youtube_id, uploaded_at, title } }
    """
    if not os.path.isfile(UPLOAD_LOG()):
        return {}
    try:
        with open(UPLOAD_LOG(), "r", encoding="utf-8") as f:
            return json.load(f)
    except Exception:
        return {}


def save_upload_log(log_data):
    """Save the upload log JSON."""
    with open(UPLOAD_LOG(), "w", encoding="utf-8") as f:
        json.dump(log_data, f, indent=2, ensure_ascii=False)


def mark_uploaded(log_data, folder_name, youtube_id, title):
    """Record a successful upload in the log."""
    log_data[folder_name] = {
        "youtube_id":   youtube_id,
        "youtube_url":  f"https://youtu.be/{youtube_id}",
        "title":        title,
        "uploaded_at":  datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    }
    save_upload_log(log_data)


# ------------------------------------------------------------
# OAUTH AUTHENTICATION
# ------------------------------------------------------------

def authenticate():
    """
    Authenticate with Google OAuth2.
    - First run: opens browser for login, saves token.json
    - Subsequent runs: loads token.json, refreshes if expired
    Returns an authenticated YouTube API service object.
    """
    if not os.path.isfile(CLIENT_SECRETS()):
        print(f"\n  ERROR: client_secrets.json not found at:")
        print(f"  {CLIENT_SECRETS()}")
        print("\n  To fix:")
        print("  1. Go to https://console.cloud.google.com")
        print("  2. APIs & Services -> Credentials")
        print("  3. Create OAuth 2.0 Client ID (Desktop app)")
        print("  4. Download JSON and save as client_secrets.json")
        print(f"  5. Place in: {SCRIPTS_DIR()}")
        sys.exit(1)

    creds = None

    # Load existing token if available
    if os.path.isfile(TOKEN_FILE):
        try:
            creds = Credentials.from_authorized_user_file(TOKEN_FILE(), SCOPES)
        except Exception:
            creds = None

    # Refresh or re-authenticate if needed
    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            try:
                creds.refresh(Request())
                log("  Token refreshed successfully.")
            except Exception:
                creds = None

        if not creds:
            print("\n  Opening browser for Google authentication...")
            print("  Log in with the Google account linked to your YouTube channel.")
            flow = InstalledAppFlow.from_client_secrets_file(CLIENT_SECRETS(), SCOPES)
            creds = flow.run_local_server(port=0)
            print("  Authentication successful.\n")

        # Save token for future runs
        with open(TOKEN_FILE(), "w") as f:
            f.write(creds.to_json())

    return build("youtube", "v3", credentials=creds)


# ------------------------------------------------------------
# CSV READER
# ------------------------------------------------------------

def load_csv():
    """
    Load youtube_uploads.csv and return list of row dicts.
    Returns empty list if file not found.
    """
    if not os.path.isfile(CSV_PATH()):
        print(f"\n  ERROR: CSV not found: {CSV_PATH()}")
        print("  Run youtube_meta.py first to generate metadata.")
        return []

    rows = []
    with open(CSV_PATH(), "r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            rows.append(row)

    return rows


# ------------------------------------------------------------
# VIDEO FILE SELECTION
# ------------------------------------------------------------

def get_upload_video(row):
    """
    Choose which video file to upload.
    Priority: video_file_music > video_file_silent
    Returns (path, is_music) or (None, False) if neither exists.
    """
    music  = row.get("video_file_music", "").strip()
    silent = row.get("video_file_silent", "").strip()

    if music and os.path.isfile(music):
        return music, True
    if silent and os.path.isfile(silent):
        return silent, False
    return None, False


# ------------------------------------------------------------
# TAG FORMATTER
# ------------------------------------------------------------

def format_tags(tags_str):
    """
    Convert comma-separated tags string to a list for the API.
    YouTube accepts up to 500 characters total for tags.
    """
    tags = [t.strip() for t in tags_str.split(",") if t.strip()]
    # Enforce YouTube 500 char limit
    result = []
    total  = 0
    for tag in tags:
        if total + len(tag) + 1 <= 500:
            result.append(tag)
            total += len(tag) + 1
    return result


# ------------------------------------------------------------
# CATEGORY ID MAP — common YouTube categories
# ------------------------------------------------------------

CATEGORY_NAMES = {
    "1":  "Film & Animation",
    "2":  "Autos & Vehicles",
    "10": "Music",
    "15": "Pets & Animals",
    "17": "Sports",
    "19": "Travel & Events",
    "20": "Gaming",
    "22": "People & Blogs",
    "23": "Comedy",
    "24": "Entertainment",
    "25": "News & Politics",
    "26": "Howto & Style",
    "27": "Education",
    "28": "Science & Technology",
    "29": "Nonprofits & Activism",
}


# ------------------------------------------------------------
# UPLOAD FUNCTIONS
# ------------------------------------------------------------

def upload_video(youtube, row, dry_run=False):
    """
    Upload a single video to YouTube with all metadata.
    Returns youtube_id on success, None on failure or skip.

    Args:
        youtube:  Authenticated YouTube API service
        row:      CSV row dict with all metadata fields
        dry_run:  If True, print what would happen but don't upload
    """
    folder_name = row.get("folder_name", "").strip()
    title       = row.get("title", "").strip()
    description = row.get("description", "").strip()
    tags_str    = row.get("tags", "").strip()
    category    = row.get("category", "19").strip()
    privacy     = row.get("privacy", "private").strip()
    kids        = row.get("made_for_kids", "yes").strip().lower() == "yes"
    thumbnail   = row.get("thumbnail", "").strip()

    # Get video file
    video_path, is_music = get_upload_video(row)
    if not video_path:
        log(f"  SKIP: No video file found for '{folder_name}'")
        return None

    tags = format_tags(tags_str)

    if dry_run:
        music_tag = "[MUSIC]" if is_music else "[SILENT]"
        print(f"\n  DRY RUN: {folder_name}")
        print(f"  Video    : {os.path.basename(video_path)} {music_tag}")
        print(f"  Title    : {title}")
        print(f"  Privacy  : {privacy}")
        print(f"  Category : {CATEGORY_NAMES.get(category, category)}")
        print(f"  Kids     : {kids}")
        print(f"  Tags     : {len(tags)} tags")
        print(f"  Thumbnail: {os.path.basename(thumbnail) if thumbnail else 'none'}")
        return "DRY_RUN"

    # ── Build request body ────────────────────────────────────
    body = {
        "snippet": {
            "title":       title[:100],     # YouTube title limit
            "description": description,
            "tags":        tags,
            "categoryId":  category,
        },
        "status": {
            "privacyStatus":          privacy,
            "selfDeclaredMadeForKids": kids,
            "license":                row.get("license", "youtube"),
        }
    }

    # ── Upload video ──────────────────────────────────────────
    log(f"  Uploading: {title[:60]}...")
    log(f"  File: {os.path.basename(video_path)}")

    media = MediaFileUpload(
        video_path,
        mimetype="video/mp4",
        resumable=True,
        chunksize=1024 * 1024 * 8   # 8MB chunks
    )

    request = youtube.videos().insert(
        part="snippet,status",
        body=body,
        media_body=media
    )

    # ── Resumable upload with progress ───────────────────────
    youtube_id = None
    response   = None

    while response is None:
        try:
            status, response = request.next_chunk()
            if status:
                pct = int(status.progress() * 100)
                print(f"  Upload progress: {pct}%", end="\r")
        except HttpError as e:
            if e.resp.status in (500, 502, 503, 504):
                # Transient server error — wait and retry
                log(f"  Server error {e.resp.status} — retrying in 10s...")
                time.sleep(10)
            else:
                log(f"  ERROR uploading '{folder_name}': {e}")
                return None

    youtube_id = response.get("id")
    print()   # Clear progress line
    log(f"  Uploaded: https://youtu.be/{youtube_id}")

    # ── Upload thumbnail ──────────────────────────────────────
    if thumbnail and os.path.isfile(thumbnail):
        try:
            log(f"  Setting thumbnail: {os.path.basename(thumbnail)}")
            youtube.thumbnails().set(
                videoId=youtube_id,
                media_body=MediaFileUpload(thumbnail)
            ).execute()
            log("  Thumbnail set.")
        except HttpError as e:
            log(f"  WARNING: Thumbnail upload failed: {e}")
            # Non-fatal — video still uploaded successfully

    return youtube_id


# ------------------------------------------------------------
# QUOTA TRACKER
# ------------------------------------------------------------

def load_quota_log():
    """Load quota_log.json keyed by date."""
    path = QUOTA_LOG()
    if not path or not os.path.isfile(path):
        return {}
    try:
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)
    except Exception:
        return {}


def save_quota_log(data):
    """Save quota log to disk."""
    path = QUOTA_LOG()
    if not path:
        return
    try:
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=2)
    except Exception as e:
        log(f"  WARNING: Could not save quota log: {e}")


def record_quota(units):
    """Add units used to today's quota log entry."""
    today = datetime.now().strftime("%Y-%m-%d")
    data  = load_quota_log()
    if today not in data:
        data[today] = {"units_used": 0}
    data[today]["units_used"] = data[today].get("units_used", 0) + units
    save_quota_log(data)


def show_quota_status():
    """Print today's quota usage."""
    today = datetime.now().strftime("%Y-%m-%d")
    data  = load_quota_log()
    used  = data.get(today, {}).get("units_used", 0)
    limit = 10000
    safe  = (limit - used) // 1650
    print(f"\n  YouTube API quota ({today}):")
    print(f"    Used      : {used:,} / {limit:,} units")
    print(f"    Remaining : {(limit-used):,} units  (~{safe} more videos)\n")


class QuotaTracker:
    """
    Tracks estimated API quota usage for the current session.
    YouTube resets quota daily at midnight Pacific time.
    This is an estimate — actual usage may vary slightly.
    """
    def __init__(self):
        self.used = 0

    def charge(self, units):
        self.used += units

    def remaining(self):
        return DAILY_QUOTA - self.used

    def can_upload(self, with_thumbnail=True):
        cost = UNITS_PER_UPLOAD + (UNITS_PER_THUMBNAIL if with_thumbnail else 0)
        return self.remaining() >= cost + QUOTA_SAFETY_BUFFER

    def report(self):
        return (f"  Quota used this session: ~{self.used} units | "
                f"Remaining: ~{self.remaining()} of {DAILY_QUOTA}")


# ------------------------------------------------------------
# MAIN UPLOAD LOOP
# ------------------------------------------------------------

def run_uploads(dry_run=False):
    show_quota_status()
    """
    Main upload loop.
    - Loads CSV and upload log
    - Skips already uploaded and missing video files
    - Stops gracefully when quota is near limit
    - Saves progress after each upload
    """
    rows       = load_csv()
    upload_log = load_upload_log()
    quota      = QuotaTracker()

    if not rows:
        return

    # ── Filter pending rows ───────────────────────────────────
    pending = []
    for row in rows:
        folder_name = row.get("folder_name", "").strip()
        if folder_name in upload_log:
            continue    # Already uploaded
        video_path, _ = get_upload_video(row)
        if not video_path:
            continue    # No video file
        pending.append(row)

    total = len(pending)

    if total == 0:
        print("\n  Nothing to upload — all rows already uploaded or missing video files.")
        return

    print(f"\n  {len(rows)} rows in CSV | {total} pending upload\n")

    if dry_run:
        print("  ── DRY RUN MODE — no actual uploads ──\n")

    # ── Upload each pending row ───────────────────────────────
    youtube    = None if dry_run else authenticate()
    done       = 0
    skipped    = 0
    quota_stop = False

    for i, row in enumerate(pending, 1):
        folder_name  = row.get("folder_name", "").strip()
        title        = row.get("title", "")[:60]
        thumbnail    = row.get("thumbnail", "").strip()
        has_thumb    = bool(thumbnail and os.path.isfile(thumbnail))

        print(f"\n  [{i}/{total}] {folder_name}")

        # Quota check
        if not dry_run and not quota.can_upload(with_thumbnail=has_thumb):
            print(f"\n  QUOTA LIMIT REACHED — stopping for today.")
            print(f"  {quota.report()}")
            print(f"  {total - done - skipped} videos remaining — resume tomorrow.")
            quota_stop = True
            break

        # Upload
        youtube_id = upload_video(youtube, row, dry_run=dry_run)

        if youtube_id and youtube_id != "DRY_RUN":
            mark_uploaded(upload_log, folder_name, youtube_id, title)
            quota.charge(UNITS_PER_UPLOAD + (UNITS_PER_THUMBNAIL if has_thumb else 0))
            done += 1
            time.sleep(UPLOAD_DELAY)
        elif youtube_id == "DRY_RUN":
            done += 1
        else:
            skipped += 1

    # ── Summary ───────────────────────────────────────────────
    print(f"\n{'='*60}")
    if dry_run:
        print(f"  DRY RUN complete. {done} would be uploaded, {skipped} skipped.")
    else:
        print(f"  Upload session complete.")
        print(f"  Uploaded : {done}")
        print(f"  Skipped  : {skipped}")
        if not quota_stop:
            print(f"  All pending videos uploaded.")
        print(f"  {quota.report()}")
    print(f"{'='*60}\n")


# ------------------------------------------------------------
# METADATA PUSH — update live video without re-uploading
# ------------------------------------------------------------

def push_metadata_update(youtube_id, title, description, tags,
                         privacy=None, category="19"):
    """
    Push updated metadata to an already-uploaded YouTube video.
    Does NOT re-upload the video — only updates text fields.
    Cost: ~50 units (vs 1,600 for a full upload).

    Args:
        youtube_id:  YouTube video ID (e.g. 'dQw4w9WgXcQ')
        title:       New title (max 100 chars)
        description: New description
        tags:        Comma-separated tags string or list
        privacy:     'public' / 'private' / 'unlisted' or None to leave unchanged
        category:    YouTube category ID (default 19 = Travel & Events)

    Returns:
        True on success, False on failure
    """
    try:
        youtube = authenticate()

        # Convert tags string to list if needed
        if isinstance(tags, str):
            tags_list = [t.strip() for t in tags.split(",") if t.strip()]
        else:
            tags_list = tags

        # Build update body — snippet contains text fields
        body = {
            "id": youtube_id,
            "snippet": {
                "title":       title[:100],
                "description": description,
                "tags":        tags_list,
                "categoryId":  category,
            }
        }

        # Add status update only if privacy change requested
        if privacy:
            body["status"] = {"privacyStatus": privacy}
            parts = "snippet,status"
        else:
            parts = "snippet"

        youtube.videos().update(
            part=parts,
            body=body
        ).execute()

        log(f"  Metadata updated: https://youtu.be/{youtube_id}")
        return True

    except HttpError as e:
        log(f"  ERROR updating metadata for {youtube_id}: {e}")
        return False
    except Exception as e:
        log(f"  ERROR: {e}")
        return False


# ------------------------------------------------------------
# FETCH LIVE METADATA — read current metadata from YouTube
# ------------------------------------------------------------

def fetch_live_metadata(youtube, youtube_id):
    """
    Fetch current title, description, tags, and privacy
    for a video directly from YouTube.
    Returns dict or None on failure.
    """
    try:
        response = youtube.videos().list(
            part="snippet,status",
            id=youtube_id
        ).execute()

        items = response.get("items", [])
        if not items:
            return None

        snippet = items[0].get("snippet", {})
        status  = items[0].get("status", {})

        return {
            "title":       snippet.get("title", ""),
            "description": snippet.get("description", ""),
            "tags":        ", ".join(snippet.get("tags", [])),
            "privacy":     status.get("privacyStatus", ""),
            "category":    snippet.get("categoryId", "19"),
        }

    except HttpError:
        return None


def fetch_all_channel_videos(youtube):
    """
    Fetch all videos on the authenticated channel.
    Returns list of dicts: { youtube_id, title, published_at, privacy }
    Handles pagination.
    """
    videos     = []
    page_token = None

    while True:
        params = {
            "part":       "id,snippet,status",
            "mine":       True,
            "type":       "video",
            "maxResults": 50,
        }
        if page_token:
            params["pageToken"] = page_token

        try:
            response   = youtube.search().list(**params).execute()
        except HttpError as e:
            log(f"  ERROR fetching channel videos: {e}")
            break

        for item in response.get("items", []):
            videos.append({
                "youtube_id":   item["id"]["videoId"],
                "title":        item["snippet"]["title"],
                "published_at": item["snippet"]["publishedAt"][:10],
                "privacy":      item.get("status", {}).get("privacyStatus", ""),
            })

        page_token = response.get("nextPageToken")
        if not page_token:
            break

    return videos


# ------------------------------------------------------------
# RESUME / STATUS
# ------------------------------------------------------------

def show_status():
    """Show upload status — what's done, what's pending."""
    rows       = load_csv()
    upload_log = load_upload_log()

    if not rows:
        return

    print(f"\n  {'FOLDER':<40} {'STATUS':<12} {'YOUTUBE ID'}")
    print(f"  {'─'*40} {'─'*12} {'─'*15}")

    for row in rows:
        folder_name = row.get("folder_name", "").strip()
        title       = row.get("title", "")[:35]
        video_path, is_music = get_upload_video(row)

        if folder_name in upload_log:
            yt_id  = upload_log[folder_name]["youtube_id"]
            status = "UPLOADED"
        elif not video_path:
            status = "NO VIDEO"
            yt_id  = ""
        else:
            status = "pending"
            yt_id  = ""

        music_tag = " [M]" if is_music else ""
        print(f"  {(folder_name + music_tag):<40} {status:<12} {yt_id}")

    uploaded = len([r for r in rows if r.get("folder_name","").strip() in upload_log])
    pending  = len([r for r in rows if r.get("folder_name","").strip() not in upload_log])
    print(f"\n  Total: {len(rows)} | Uploaded: {uploaded} | Pending: {pending}\n")


# ------------------------------------------------------------
# MAIN
# ------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description="CatsofTravels YouTube Uploader")
    parser.add_argument("--dryrun", action="store_true",
                        help="Show what would be uploaded without actually uploading")
    args = parser.parse_args()

    print("╔══════════════════════════════════════════════════════╗")
    print("║      CatsofTravels — YouTube Uploader                ║")
    print("║                youtube_upload.py                     ║")
    print("║                Version 1.1.0                         ║")
    print("╚══════════════════════════════════════════════════════╝")
    print()

    if args.dryrun:
        print("  DRY RUN MODE — no uploads will be made.\n")
        run_uploads(dry_run=True)
        return

    print("  SELECT ACTION")
    print("  U. Upload pending videos")
    print("  S. Show upload status")
    print("  D. Dry run — preview without uploading")
    print("  Q. Quit")
    print()

    while True:
        choice = input("  Choice: ").strip().upper()
        if choice in ("U", "S", "D", "Q"):
            break
        print("  Invalid choice.")

    if choice == "Q":
        print("  Goodbye.")
        return
    elif choice == "S":
        show_status()
    elif choice == "D":
        run_uploads(dry_run=True)
    elif choice == "U":
        # Confirm before uploading
        rows       = load_csv()
        upload_log = load_upload_log()
        pending    = [r for r in rows
                      if r.get("folder_name","").strip() not in upload_log
                      and get_upload_video(r)[0] is not None]

        if not pending:
            print("\n  Nothing pending — all videos already uploaded.")
            return

        print(f"\n  {len(pending)} video(s) ready to upload.")
        print("  YouTube free quota allows ~6 videos per day.")
        print()
        confirm = input("  Proceed? Y/N: ").strip().upper()
        if confirm == "Y":
            run_uploads(dry_run=False)
        else:
            print("  Cancelled.")


if __name__ == "__main__":
    main()


# ------------------------------------------------------------
# LIVE METADATA — fetch and push to YouTube
# ------------------------------------------------------------

def get_live_video_metadata(youtube, youtube_id):
    """
    Fetch current title, description, tags, privacy, and category
    for a live video by its YouTube ID.
    Returns dict or None on failure.
    Used by UC6 (View & Edit Live Metadata).
    """
    try:
        response = youtube.videos().list(
            part="snippet,status",
            id=youtube_id
        ).execute()

        items = response.get("items", [])
        if not items:
            return None

        snippet = items[0]["snippet"]
        status  = items[0]["status"]

        return {
            "youtube_id":         youtube_id,
            "title":              snippet.get("title", ""),
            "description":        snippet.get("description", ""),
            "tags":               ", ".join(snippet.get("tags", [])),
            "category":           snippet.get("categoryId", "19"),
            "privacy":            status.get("privacyStatus", "private"),
            "published_at":       snippet.get("publishedAt", "")[:10],
            "made_for_kids":      status.get("selfDeclaredMadeForKids", False),
            "license":            status.get("license", "youtube"),
            "embeddable":         status.get("embeddable", True),
            "public_stats":       status.get("publicStatsViewable", True),
            "default_language":   snippet.get("defaultLanguage", "en"),
            "audio_language":     snippet.get("defaultAudioLanguage", "en"),
        }

    except HttpError as e:
        log(f"  ERROR fetching metadata for {youtube_id}: {e}")
        return None


def push_metadata_update(youtube, youtube_id, title, description, tags_str,
                         privacy=None, category="19",
                         made_for_kids=False, license="youtube",
                         embeddable=True, public_stats=True,
                         default_language="en", audio_language="en",
                         paid_promo=False):
    """
    Push updated title, description, and tags to a live YouTube video.
    Does NOT re-upload the video — only updates metadata.
    Cost: ~50 API units (very cheap vs 1600 for upload).

    Args:
        youtube:     Authenticated YouTube API service
        youtube_id:  YouTube video ID to update
        title:       New title (max 100 chars)
        description: New description
        tags_str:    Comma-separated tags string
        privacy:     Optional — public/private/unlisted. None = keep existing.
        category:    YouTube category ID (default 19 = Travel & Events)

    Returns True on success, False on failure.
    """
    try:
        # First fetch existing snippet to preserve fields we're not changing
        existing = get_live_video_metadata(youtube, youtube_id)
        if not existing:
            log(f"  ERROR: Could not fetch existing metadata for {youtube_id}")
            return False

        tags = [t.strip() for t in tags_str.split(",") if t.strip()]

        # Resolve privacy — use passed value or fall back to existing
        resolved_privacy = privacy if privacy else (existing.get("privacy") or "private")

        body = {
            "id": youtube_id,
            "snippet": {
                "title":                title[:100],
                "description":          description,
                "tags":                 tags,
                "categoryId":           category,
                "defaultLanguage":      default_language,
                "defaultAudioLanguage": audio_language,
            },
            "status": {
                "privacyStatus":              resolved_privacy,
                "selfDeclaredMadeForKids":    made_for_kids,
                "license":                    license,
                "embeddable":                 embeddable,
                "publicStatsViewable":        public_stats,
                "containsSyntheticMedia":     False,
                "madeForKids":                made_for_kids,
            }
        }

        youtube.videos().update(
            part="snippet,status",
            body=body
        ).execute()

        log(f"  Updated: https://youtu.be/{youtube_id}")
        log(f"  Title: {title[:60]}")
        return True

    except HttpError as e:
        log(f"  ERROR pushing metadata for {youtube_id}: {e}")
        return False
